#!/usr/bin/env bash

################################################################################
# AUTOR: Victor Dias Marques                                                   #
# CONTATO: victordmarx@pm.me                                                   #
# DATA: 28/09/2025                                                             #
# DESCRIÇÃO: exibe um cabeçalho personalizado sempre que abre o terminal       #
################################################################################
# VERSÃO: v1.1.0                                                               #
# HISTÓRICO:                                                                   #
#   1.1.0 - 01/10/2025 							       #
#       MELHORIA							       #
#	  - Ascii art alterada para versão 43.				       #
#         - Cor alterada para azul.                                            #
#   1.0.0 - 28/09/2025 - Versão inicial                                        #
################################################################################

RESET='\033[0m'
BLUE='\033[38;5;39m'

echo -e "${BLUE}"

echo "***********************************************************************"
echo "*                                                                     *"
echo "*      _____        _                                                 *"
echo "*     |  ___|__  __| | ___  _ __ __ _                                 *"
echo "*     | |_ / _ \/ _  |/ _ \| '__/ _' |                                *"
echo "*     |  _|  __/ (_| | (_) | | | (_| |                                *"
echo "*     |_|__\___|\__,_|\___/|_|  \__,_|_              _  _  _____      *"
echo "*     / ___|(_) |_   _____ _ __| |__ | |_   _  ___  | || ||___ /      *"
echo "*     \___ \| | \ \ / / _ \ '__| '_ \| | | | |/ _ \ | || |_ |_ \      *"
echo "*      ___) | | |\ V /  __/ |  | |_) | | |_| |  __/ |__   _|__) |     *"
echo "*     |____/|_|_| \_/ \___|_|  |_.__/|_|\__,_|\___|    |_||____/      *"
echo "*                                                                     *"
echo "***********************************************************************"

echo "Usuário: $USER"
echo "Kernel: $(uname -r)"
echo "Data: $(date '+%d/%m/%Y')"
echo "Hora: $(date '+%T')"
echo "Data estelar: $(stardate)"
echo "Data imperial: $(imperial_date)"
echo "Uptime: $(uptime -p)"
